theme: jekyll-theme-architect
title: Universal Playables
description: A mod full of playable characters for Friday Night Funkin', + PLAYABLE MODS!
favicon: /favicon.ico
background: /images/E136WWRWEAAnM23.png